//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره مبین قطعه آسیا.
        /// </summary>
        public static string AboutGasso {
            get {
                return ResourceManager.GetString("AboutGasso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهران، خ شهید بهشتی، خ احمدقصیر، کوچه یکم، پلاک 1، طبقه 2.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلومتر 37 جاده خاوران، شهرک صنعتی عباس آباد، بلوار ابن سینا، خیابان 11، پلاک 771.
        /// </summary>
        public static string AdressDetail {
            get {
                return ResourceManager.GetString("AdressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات پس از فروش.
        /// </summary>
        public static string AfterSaleServices {
            get {
                return ResourceManager.GetString("AfterSaleServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهترین کیفیت.
        /// </summary>
        public static string BestQuality {
            get {
                return ResourceManager.GetString("BestQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم پیوستن به ما.
        /// </summary>
        public static string CareerForm {
            get {
                return ResourceManager.GetString("CareerForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گواهینامه ها.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازرگانی.
        /// </summary>
        public static string Commerce {
            get {
                return ResourceManager.GetString("Commerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات برجسته مبین قطعه آسیا.
        /// </summary>
        public static string CompanyServices {
            get {
                return ResourceManager.GetString("CompanyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مبین قطعه آسیا با بیش از 50 سال فعالیت تولیدی علاوه بر محصولات تولیدی خود خدماتی را به مشتریان خود ارائه می کند.
        /// </summary>
        public static string CompanyServicesDesc {
            get {
                return ResourceManager.GetString("CompanyServicesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی حقوق این وب سایت متعلق به شرکت مبین قطعه آسیا می باشد. طراحی وب سایت: .
        /// </summary>
        public static string CopyRights {
            get {
                return ResourceManager.GetString("CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری راضی.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر جزییات.
        /// </summary>
        public static string DetailImages {
            get {
                return ResourceManager.GetString("DetailImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیروی کار.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فکس.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 ماه گارانتی محصول.
        /// </summary>
        public static string garanty {
            get {
                return ResourceManager.GetString("garanty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مبین قطعه آسیا.
        /// </summary>
        public static string GassoCompany {
            get {
                return ResourceManager.GetString("GassoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات مبین قطعه آسیا.
        /// </summary>
        public static string GassoServices {
            get {
                return ResourceManager.GetString("GassoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مطالب وبلاگ.
        /// </summary>
        public static string latestBlog {
            get {
                return ResourceManager.GetString("latestBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این قسمت آخرین مطالب وبلاگ و آخرین اخبار شرکت مبین قطعه آسیا را مشاهده خواهید کرد.
        /// </summary>
        public static string LatestBlogDesc {
            get {
                return ResourceManager.GetString("LatestBlogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین اخبار مبین قطعه آسیا.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدیدترین اخبار و مقالات شرکت مبین قطعه آسیا را از وب سایت این شرکت دنبال نمایید.
        /// </summary>
        public static string LatestNewsDesc {
            get {
                return ResourceManager.GetString("LatestNewsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت مکانی.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوستن به ما.
        /// </summary>
        public static string MenuCareer {
            get {
                return ResourceManager.GetString("MenuCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود کاتالوگ.
        /// </summary>
        public static string MenuCatalog {
            get {
                return ResourceManager.GetString("MenuCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری تصاویر.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        public static string MenuNews {
            get {
                return ResourceManager.GetString("MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        public static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string MenuService {
            get {
                return ResourceManager.GetString("MenuService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدیدترین محصولات.
        /// </summary>
        public static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبر نامه.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر خدمات.
        /// </summary>
        public static string OtherService {
            get {
                return ResourceManager.GetString("OtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان ما.
        /// </summary>
        public static string OurCustomer {
            get {
                return ResourceManager.GetString("OurCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برخی از مشتریان شرکت مبین قطعه آسیا.
        /// </summary>
        public static string OurCustomerDesc {
            get {
                return ResourceManager.GetString("OurCustomerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک های مفید.
        /// </summary>
        public static string PopularLinks {
            get {
                return ResourceManager.GetString("PopularLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روابط عمومی.
        /// </summary>
        public static string Pr {
            get {
                return ResourceManager.GetString("Pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه مطلب.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات مرتبط.
        /// </summary>
        public static string RelatedProduct {
            get {
                return ResourceManager.GetString("RelatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروش.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده محصولات.
        /// </summary>
        public static string ShowProduct {
            get {
                return ResourceManager.GetString("ShowProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات بیشتر.
        /// </summary>
        public static string SliderMore {
            get {
                return ResourceManager.GetString("SliderMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با شعار اینکه کیفیت یک مسیر است نه یک مقصد.
        /// </summary>
        public static string slogan1 {
            get {
                return ResourceManager.GetString("slogan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه های اجتماعی.
        /// </summary>
        public static string SocialNetwork {
            get {
                return ResourceManager.GetString("SocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات فنی.
        /// </summary>
        public static string Specefication {
            get {
                return ResourceManager.GetString("Specefication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل خود را وارد نمایید.
        /// </summary>
        public static string SubmitEmail {
            get {
                return ResourceManager.GetString("SubmitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت پیغام.
        /// </summary>
        public static string SubmitMessage {
            get {
                return ResourceManager.GetString("SubmitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست.
        /// </summary>
        public static string SubmitRequest {
            get {
                return ResourceManager.GetString("SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمای سه بعدی.
        /// </summary>
        public static string ThreeDView {
            get {
                return ResourceManager.GetString("ThreeDView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما | مبین قطعه آسیا.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست همکاری در شرکت مبین قطعه آسیا.
        /// </summary>
        public static string TitleCareer {
            get {
                return ResourceManager.GetString("TitleCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما | مبین قطعه آسیا.
        /// </summary>
        public static string TitleContact {
            get {
                return ResourceManager.GetString("TitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری تصاویر مبین قطعه آسیا.
        /// </summary>
        public static string TitleGalleryList {
            get {
                return ResourceManager.GetString("TitleGalleryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار مبین قطعه آسیا.
        /// </summary>
        public static string TitleNewsList {
            get {
                return ResourceManager.GetString("TitleNewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک های مفید.
        /// </summary>
        public static string usefullLinks {
            get {
                return ResourceManager.GetString("usefullLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده جزییات.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال سابقه.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زاوش.
        /// </summary>
        public static string Zavosh {
            get {
                return ResourceManager.GetString("Zavosh", resourceCulture);
            }
        }
    }
}
